version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
      docker: 18
  pre_build:
    commands:
      - echo Loggin in to Amazon ECR...
      - aws --version
      - docker login -u AWS -p eyJwYXlsb2FkIjoiT21CUUl3allhNlRoZUx5QkcwNFBrQ3dmSzZHQVlFVU0zRDkzd3hoUVhWSktHMmp4ZDd5ZGx1N1FqQms3a01HWlVsOWpneE5ycUlaUXFzbFpMOENaSkZWRW8yUWlHUDlQOS90VU1qZEJJRGdFemlFMXFPTjVTZ2ZxQTd6SDRGTklFdENjMzRUd2VCQlFNYVh1M1E4VEdHa1U3TDNEbFRnM1JUVFdaY0hyMmhKTkd3a1pRODJNd0kydHVjZEVPZ0lCVTBnMzNnYnFUWHA4cjM1ajFEd0N6aVJ1ZGR6REp0ZG9XTUdRYVNNNFVteVZDalBmdkg0bk1oMG0wUVI1cXpiOUN6TlYyTXFFekNhUUY2c3ExVTlrU1hJeGpTVU1Lbmh0SDZFZnM3NGw1ak5YMEZ0aGwxYlg2QmpyUEhxclp0OHNKUEpxcEw2VHJqQXZhUTdRQ2RMQnJyaVVqM002UzBPUFNhZ2pEODBMcmprMU5KTzBoSVRMdHZZV0tVY05JUWM2YlhVazJNYkpVNTNnRldWdmNic3RoRE1OTWNQa2lxWXBGb1BVenJiUTRkU3dKL2ZMUWE5RFVQdlZsRXRRakFSZFhKK1kxTHY5VzROdVJmblJvTVdFeUozMkREaTBtN3Zib3NSbmZXRlpjUmRTaFRPN2Q5SGZaVWYxSFk3UTlmeFVZbWhuQzY4SVFMZFlzZGRQcHdUSERla0J6YVB3dEFLZTRZYUN3aVdTNWM2U3pSa3k0TTdHQmxmZThBSVR5Q3lvMVZVY1dMOXI2c0Y1WXA4TTJLRmFIMzlDZno3S2tQd2VVU2I5RVRXbzl4VFc0MkhzM1h4VmxMUERZTVhFTEwzdU8raFVLT04rbWlrSG1kNkNsVUdMQ1dWSXNhNlIzZlp5QU9GS0YrbnF1TWIrTmUvQjIwcmFERnZ6ZmFnOE1DWVJtZCtsb2tZZTBhOTVmUTg2cEY3MjNLb21jZnlJdTJJVmZzdkVWMC9SYmU1cFQ3TS95TjU4V3E3dnRXdlFKQVNISDZVQzZVaG5uOER3QUVicFVaa05UNlZKdkdQczV6UldCdVNSa0tNb3NmbUVFYzVqWVJXWWZhYjhGMXI2Y2RmdzZNUXNIRDZKTUhDT2l6Y0NlbHR0MVNwbXRyMW40VWVxZGRkK0dqWWhHRkxRdFBVMFRDdWluUXdFZmNydVBYODV6K1hZVTEzb0tML0FUTnFqUXlKcEFDUmN5ZDdlbGRKV1hPdDBJTktJSmluWGsyaEZONytLUElrNmY4SHRESnpVOWpCbzdrTEJ5ckdxMUpWSE5aNzlBTm5ZS3E0aS9XQ2JVSmhlWThZdTllRDRLSStpU0YvYlFrdFMzYjgvNi81ZFYzK2Nza09BVitNYm4vcG5kNDE3TVdkQ1FMczVoaXA0WllPY2Q5bTlCZVRWeW82dFdtbi9uWVc3Zk0xbXVjWjFNbGdwUjRMNVF0V09jMjhHSzB1czdUTlRxK2dKOGdrZHhMRjFOR253VWt2VHNnPT0iLCJkYXRha2V5IjoiQVFFQkFIaHdtMFlhSVNKZVJ0Sm01bjFHNnVxZWVrWHVvWFhQZTVVRmNlOVJxOC8xNHdBQUFINHdmQVlKS29aSWh2Y05BUWNHb0c4d2JRSUJBREJvQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFREs0NnkzT3dxV2lmZ3dkYnR3SUJFSUE3ak4wcHIxU3hQcGtqbjBnejlzcnhsUlE0eHlZUE1mTllRZHFpTWlTaFBOK3R2VDkrdlFKQzZXZVJZYW5ybDExbE1ScHRpWTVGWjdaWWE3ND0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE1Nzg3MDYwMzB9 https://472348108051.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=472348108051.dkr.ecr.us-east-1.amazonaws.com/orma/hello-cicd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building docker image...
      - docker build -t orma/hello-cicd
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      