version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
      docker: 18
  pre_build:
    commands:
      - echo Loggin in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --registry-ids 472348108051)
      - REPOSITORY_URI=472348108051.dkr.ecr.us-east-1.amazonaws.com/orma/hello-cicd
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building docker image...
      - docker build -t orma/hello-cicd
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      